
######################################################################
#                                                                    #
#  Main playbook for declaring a configuration actions to all nodes  #
#                                                                    #
######################################################################



# Configure a bare server node as a DAQ server
- hosts: daq_servers
  remote_user: vagrant
  become: true

  # feedsome test DAQ instance as server node
  roles:
    - base_server_node
    - web_server_node


