# Main task for configuring feedsome base server nodes

---
  - name: "upgrade all packages"
    yum:
      name: '*'
      state: latest

  - name: "Create a system user for deploying applications"
    user:
      name: deploy
      system: yes
      shell: /bin/false
      generate_ssh_key: yes

  - name: "Set authorized key took from file"
    authorized_key:
      user: deploy
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
